"""Generate and load stable Torch bridges from a native :class:`KernelDef`.

The generated extension contains only Torch-to-``CallAbi`` adaptation and a
process-local operator handle. Kernel selection, caching, and JIT compilation
remain in vecops C++ runtime code, so a call never uses a Python dispatch
callback. The module-level template is intentionally kept outside generation
functions to make its ABI surface reviewable as ordinary source text.
"""

from __future__ import annotations

import hashlib
import keyword
import os
import re
from pathlib import Path
from string import Template
from threading import Lock
from typing import Any

from . import _C as native

_registrations: dict[tuple[str, str], Any] = {}
_registration_lock = Lock()
_identifier = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _require_identifier(value: str, what: str) -> None:
  """Reject names that cannot safely become generated C++ identifiers."""
  if not _identifier.fullmatch(value) or keyword.iskeyword(value):
    raise ValueError(f"{what} must be a C++ identifier, got {value!r}")


def _dtype_name(dtype: native.DType) -> str:
  return str(dtype).rsplit(".", 1)[-1]


_dtype_abi = {
  "bool_": "VECOPS_DTYPE_BOOL",
  "int8": "VECOPS_DTYPE_I8",
  "uint8": "VECOPS_DTYPE_U8",
  "int16": "VECOPS_DTYPE_I16",
  "uint16": "VECOPS_DTYPE_U16",
  "int32": "VECOPS_DTYPE_I32",
  "uint32": "VECOPS_DTYPE_U32",
  "int64": "VECOPS_DTYPE_I64",
  "uint64": "VECOPS_DTYPE_U64",
  "float16": "VECOPS_DTYPE_F16",
  "bfloat16": "VECOPS_DTYPE_BF16",
  "float32": "VECOPS_DTYPE_F32",
  "float64": "VECOPS_DTYPE_F64",
}


def _scalar_cpp(dtype: native.DType) -> str:
  name = _dtype_name(dtype)
  if name == "bool_":
    return "bool"
  if name.startswith("float") or name == "bfloat16":
    return "double"
  return "int64_t"


def _scalar_schema(dtype: native.DType) -> str:
  name = _dtype_name(dtype)
  if name == "bool_":
    return "bool"
  if name.startswith("float") or name == "bfloat16":
    return "float"
  return "int"


def _schema_default(value: Any) -> str:
  if isinstance(value, bool):
    return "True" if value else "False"
  return repr(value)


def _torch_schema(
    name: str, definition: native.KernelDef, *, return_outputs: bool = False
) -> str:
  """Lower a KernelDef to a mutable out-style Torch dispatcher schema."""
  arguments: list[str] = []
  outputs: list[str] = []
  alias = ord("a")
  parameters = definition.inputs
  for index, parameter in enumerate(parameters):
    _require_identifier(parameter.name, "kernel parameter name")
    if isinstance(parameter, native.TensorDef):
      if parameter.output and parameter.optional:
        raise ValueError("Torch bridge output tensors must be present and caller-allocated")
      if parameter.output:
        tensor_type = f"Tensor({chr(alias)}!)"
        # The public wrapper returns the caller-owned output argument.  The
        # internal Torch op only needs a Tensor result so older Inductor
        # custom-op wrappers do not reject a void return.  Keep the result
        # unannotated: AOT functionalization cannot represent a custom-op
        # output that aliases a mutable argument, while mutation tracking is
        # already carried by the argument's (a!) annotation.
        outputs.append("Tensor")
        alias += 1
      else:
        tensor_type = "Tensor"
      if parameter.optional:
        tensor_type += "?"
      arguments.append(f"{tensor_type} {parameter.name}")
    else:
      item = f"{_scalar_schema(parameter.dtype)} {parameter.name}"
      if parameter.default is not None:
        item += f"={_schema_default(parameter.default.value)}"
      arguments.append(item)
  for symbol, symbol_type in definition.values.items():
    _require_identifier(symbol, "specialization value name")
    torch_type = "int?" if symbol_type == native.ConstInt else "ScalarType?"
    arguments.append(f"{torch_type} __spec_{symbol}=None")
  returns = "()"
  if return_outputs:
    if len(outputs) == 1:
      returns = outputs[0]
    elif outputs:
      returns = f"({', '.join(outputs)})"
  return f"{name}({', '.join(arguments)}) -> {returns}"


_TORCH_BRIDGE_TEMPLATE = Template(
  r"""// Generated by vecops; do not edit.
#include <ATen/ATen.h>
#include <c10/core/ScalarType.h>
#include <torch/extension.h>
#include <torch/library.h>

#include <array>
#include <atomic>
#include <cstdint>
#include <cstring>
#include <optional>
#include <tuple>
#include <vector>

#include "vecops/runtime/OperatorBridgeAbi.h"

namespace {
std::atomic<uint64_t> operator_handle{0};

uint32_t dtype_to_abi(c10::ScalarType dtype) {
  switch (dtype) {
  case c10::ScalarType::Bool: return VECOPS_DTYPE_BOOL;
  case c10::ScalarType::Char: return VECOPS_DTYPE_I8;
  case c10::ScalarType::Byte: return VECOPS_DTYPE_U8;
  case c10::ScalarType::Short: return VECOPS_DTYPE_I16;
  case c10::ScalarType::Int: return VECOPS_DTYPE_I32;
  case c10::ScalarType::Long: return VECOPS_DTYPE_I64;
  case c10::ScalarType::Half: return VECOPS_DTYPE_F16;
  case c10::ScalarType::BFloat16: return VECOPS_DTYPE_BF16;
  case c10::ScalarType::Float: return VECOPS_DTYPE_F32;
  case c10::ScalarType::Double: return VECOPS_DTYPE_F64;
  default: TORCH_CHECK(false, "vecops does not support Torch dtype ", dtype);
  }
}

VecopsValue make_tensor(const at::Tensor* tensor, uint64_t flags) {
  VecopsValue value{}; value.struct_size = sizeof(VecopsValue);
  if (!tensor) { value.kind = VECOPS_VALUE_NONE; return value; }
  TORCH_CHECK(tensor->defined(), "vecops received an undefined tensor");
  TORCH_CHECK(tensor->device().is_cpu(), "vecops generated bridge currently accepts CPU tensors only");
  TORCH_CHECK(tensor->layout() == c10::Layout::Strided, "vecops requires strided Torch tensors");
  const auto sizes = tensor->sizes();
  const auto strides = tensor->strides();
  value.kind = VECOPS_VALUE_TENSOR;
  value.value.tensor = VecopsTensorView{
    sizeof(VecopsTensorView),
    (flags & VECOPS_TENSOR_WRITE) ? const_cast<at::Tensor*>(tensor)->mutable_data_ptr()
                                  : const_cast<void*>(tensor->const_data_ptr()),
    0, VECOPS_DEVICE_CPU, tensor->device().index(), dtype_to_abi(tensor->scalar_type()),
    static_cast<uint32_t>(tensor->dim()), sizes.data(), strides.data(),
    flags
  };
  return value;
}

VecopsValue make_signed_value(int64_t input, uint32_t dtype) {
  VecopsValue value{}; value.struct_size = sizeof(value); value.kind = VECOPS_VALUE_SCALAR;
  value.value.scalar.struct_size = sizeof(VecopsScalar); value.value.scalar.dtype = dtype;
  value.value.scalar.value.i64 = input; return value;
}
VecopsValue make_unsigned_value(uint64_t input, uint32_t dtype) {
  VecopsValue value{}; value.struct_size = sizeof(value); value.kind = VECOPS_VALUE_SCALAR;
  value.value.scalar.struct_size = sizeof(VecopsScalar); value.value.scalar.dtype = dtype;
  value.value.scalar.value.u64 = input; return value;
}
VecopsValue make_float_value(double input, uint32_t dtype) {
  VecopsValue value{}; value.struct_size = sizeof(value); value.kind = VECOPS_VALUE_SCALAR;
  value.value.scalar.struct_size = sizeof(VecopsScalar); value.value.scalar.dtype = dtype;
  value.value.scalar.value.f64 = input; return value;
}
VecopsSpecializationArgument make_integer_spec(const char* name, int64_t input) {
  VecopsSpecializationArgument value{}; value.struct_size = sizeof(value);
  value.kind = VECOPS_SPECIALIZATION_CONST_INT; value.name = name; value.value.integer = input; return value;
}
VecopsSpecializationArgument make_dtype_spec(const char* name, uint32_t input) {
  VecopsSpecializationArgument value{}; value.struct_size = sizeof(value);
  value.kind = VECOPS_SPECIALIZATION_DTYPE; value.name = name; value.value.dtype = input; return value;
}

$cpp_return_type wrapper($cpp_parameters) {
  std::array<VecopsValue, $parameter_count> values{};
$append_arguments
  std::array<VecopsSpecializationArgument, $specialization_count> specs{};
  uint32_t spec_count = 0;
$append_specializations
  VecopsCall call{sizeof(VecopsCall), static_cast<uint32_t>(values.size()), values.data(), nullptr, 0, nullptr};
  std::array<char, 1024> message{};
  VecopsError error{sizeof(VecopsError), 0, message.data(), message.size(), 0};
  const auto result = vecops_operator_bridge_invoke_v1(
    operator_handle.load(std::memory_order_acquire), &call, spec_count, specs.data(), &error);
  TORCH_CHECK(result == VECOPS_STATUS_OK, message.data());
$return_outputs
}

$cpp_return_type meta_wrapper($cpp_parameters) {
$return_outputs
}
} // namespace

TORCH_LIBRARY_FRAGMENT($library, library) {
  library.def("$schema");
}
TORCH_LIBRARY_IMPL($library, CPU, library) {
  library.impl("$name", &wrapper);
}
TORCH_LIBRARY_IMPL($library, Meta, library) {
  library.impl("$name", &meta_wrapper);
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, module) {
  module.def("_set_handle", [](uint64_t handle) { operator_handle.store(handle, std::memory_order_release); });
}
"""
)


def _generate_torch_source(
    library: str,
    name: str,
    definition: native.KernelDef,
    *,
    return_outputs: bool = False,
) -> str:
  """Generate the complete bridge translation unit without writing it to disk."""
  schema = _torch_schema(
      name, definition, return_outputs=return_outputs
  ).replace("\\", "\\\\").replace('"', '\\"')
  parameters = definition.inputs
  cpp_parameters: list[str] = []
  call_append: list[str] = []
  for index, parameter in enumerate(parameters):
    local = f"p{index}"
    if isinstance(parameter, native.TensorDef):
      access = parameter.access
      flags = (
        "VECOPS_TENSOR_READ | VECOPS_TENSOR_WRITE"
        if access == native.TensorAccess.inout
        else "VECOPS_TENSOR_WRITE"
        if access == native.TensorAccess.output
        else "VECOPS_TENSOR_READ"
      )
      if parameter.optional:
        cpp_parameters.append(f"std::optional<at::Tensor> {local}")
        call_append.append(f"  values[{index}] = make_tensor({local}.has_value() ? &*{local} : nullptr, {flags});")
      else:
        tensor_type = "at::Tensor&" if parameter.output else "const at::Tensor&"
        cpp_parameters.append(f"{tensor_type} {local}")
        call_append.append(f"  values[{index}] = make_tensor(&{local}, {flags});")
    else:
      cpp_parameters.append(f"{_scalar_cpp(parameter.dtype)} {local}")
      dtype = _dtype_abi[_dtype_name(parameter.dtype)]
      kind = _dtype_name(parameter.dtype)
      if kind == "bool_" or kind.startswith("uint"):
        storage = f"make_unsigned_value({local}, {dtype})"
      elif kind.startswith("int"):
        storage = f"make_signed_value({local}, {dtype})"
      else:
        storage = f"make_float_value({local}, {dtype})"
      call_append.append(f"  values[{index}] = {storage};")

  spec_append: list[str] = []
  for index, (symbol, symbol_type) in enumerate(definition.values.items()):
    local = f"s{index}"
    if symbol_type == native.ConstInt:
      cpp_parameters.append(f"std::optional<int64_t> {local}")
      spec_append.append(f'  if ({local}) specs[spec_count++] = make_integer_spec("{symbol}", *{local});')
    else:
      cpp_parameters.append(f"std::optional<c10::ScalarType> {local}")
      spec_append.append(f'  if ({local}) specs[spec_count++] = make_dtype_spec("{symbol}", dtype_to_abi(*{local}));')

  output_locals = [
      f"p{index}"
      for index, parameter in enumerate(parameters)
      if isinstance(parameter, native.TensorDef) and parameter.output
  ]
  cpp_return_type = "void"
  return_statement = ""
  if return_outputs and len(output_locals) == 1:
    cpp_return_type = "at::Tensor"
    return_statement = f"  return {output_locals[0]};"
  elif return_outputs and output_locals:
    cpp_return_type = "std::tuple<" + ", ".join(
        "at::Tensor" for _ in output_locals
    ) + ">"
    return_statement = f"  return std::make_tuple({', '.join(output_locals)});"

  return _TORCH_BRIDGE_TEMPLATE.substitute(
    schema=schema,
    cpp_parameters=", ".join(cpp_parameters),
    parameter_count=len(parameters),
    append_arguments=os.linesep.join(call_append),
    specialization_count=len(definition.values),
    append_specializations=os.linesep.join(spec_append),
    cpp_return_type=cpp_return_type,
    return_outputs=return_statement,
    library=library,
    name=name,
  )


def _public_wrapper(library: str, name: str, definition: native.KernelDef, torch_op: Any, operator: native.Operator):
  """Wrap raw ``torch.ops`` positional specializations in the public call form."""
  parameters = list(definition.inputs)
  symbols = list(definition.values)
  output_indices = [
    index for index, parameter in enumerate(parameters) if isinstance(parameter, native.TensorDef) and parameter.output
  ]

  def invoke(*args, **kwargs):
    if len(args) > len(parameters):
      raise TypeError(f"{library}.{name} expected at most {len(parameters)} positional arguments")
    ordered = list(args)
    for parameter in parameters[len(ordered) :]:
      if parameter.name in kwargs:
        ordered.append(kwargs.pop(parameter.name))
      elif isinstance(parameter, native.TensorDef) and parameter.optional:
        ordered.append(None)
      elif isinstance(parameter, native.ValueDef) and parameter.default is not None:
        ordered.append(parameter.default.value)
      else:
        raise TypeError(f"missing required argument: {parameter.name}")
    spec_values = [kwargs.pop(symbol, None) for symbol in symbols]
    if kwargs:
      unexpected = next(iter(kwargs))
      raise TypeError(f"unexpected keyword argument: {unexpected}")
    outputs = tuple(ordered[index] for index in output_indices)
    from ._precompile import maybe_collect_call

    collected = maybe_collect_call(
      operator,
      definition,
      ordered,
      dict(zip(symbols, spec_values)),
      name=f"{library}::{name}",
    )
    if not collected:
      torch_op(*ordered, *spec_values)
    if len(outputs) == 1:
      return outputs[0]
    return outputs

  invoke.__name__ = name
  invoke.__qualname__ = f"vecops.ops.torch.{library}.{name}"
  invoke.__doc__ = f"Generated mutable vecops wrapper for {library}::{name}."
  invoke._vecops_operator = operator
  return invoke


def register_torch_operator(
  library: str,
  name: str,
  operator: native.Operator,
  kernel_def: native.KernelDef,
  *,
  build_directory: str | os.PathLike[str] | None = None,
  verbose: bool = False,
  extra_cflags: tuple[str, ...] = (),
  return_outputs: bool = False,
):
  """Compile/register one mutable Torch bridge and return its public wrapper.

  Registration is idempotent per ``(library, name)`` in this Python process.
  Bridge source and extension output are placed below ``build_directory`` or a
  deterministic user-cache subdirectory.  Importing Torch is intentionally
  deferred until registration; bridge compilation is a normal external C++
  build and may take substantial time.
  """
  _require_identifier(library, "Torch library name")
  _require_identifier(name, "Torch operator name")
  key = (library, name)
  with _registration_lock:
    if key in _registrations:
      return _registrations[key]

    import torch
    from torch.utils.cpp_extension import load

    source = _generate_torch_source(
      library, name, kernel_def, return_outputs=return_outputs
    )
    native_library = Path(native.__file__).resolve()
    # A bridge calls the handle registry exported by this exact extension.
    # Schema-identical vecops installations must not share one cached bridge:
    # doing so can leave DT_NEEDED pointing at another `_C`, while `_set_handle`
    # registers the operator in the current module's independent registry.
    bridge_identity = f"{source}\0{native_library}"
    digest = hashlib.sha256(bridge_identity.encode()).hexdigest()[:16]
    if build_directory is None:
      from ._compiler import default_cache_dir

      bridge_cache = os.environ.get("VECOPS_TORCH_BRIDGE_DIR")
      bridge_base = (
          Path(bridge_cache).expanduser().resolve()
          if bridge_cache
          else default_cache_dir() / "torch-bridges"
      )
      bridge_root = bridge_base / f"{library}_{name}_{digest}"
    else:
      bridge_root = Path(build_directory).expanduser().resolve()
    bridge_root.mkdir(parents=True, exist_ok=True)
    source_path = bridge_root / "bridge.cpp"
    if not source_path.exists() or source_path.read_text() != source:
      source_path.write_text(source)

    include_root = Path(__file__).resolve().parents[2] / "include"
    configured_root = os.environ.get("VECOPS_SOURCE_ROOT")
    if configured_root:
      include_root = Path(configured_root).expanduser().resolve() / "include"
    if not (include_root / "vecops" / "runtime" / "OperatorBridgeAbi.h").is_file():
      packaged = Path(__file__).resolve().parent / "_sdk" / "include"
      if (packaged / "vecops" / "runtime" / "OperatorBridgeAbi.h").is_file():
        include_root = packaged
      else:
        raise RuntimeError("vecops framework bridge headers were not found")

    module = load(
      name=f"vecops_bridge_{library}_{name}_{digest}",
      sources=[str(source_path)],
      extra_cflags=["-O3", "-std=c++20", *extra_cflags],
      extra_ldflags=[str(native_library), f"-Wl,-rpath,{native_library.parent}"],
      extra_include_paths=[str(include_root)],
      build_directory=str(bridge_root),
      verbose=verbose,
      with_cuda=False,
      is_python_module=True,
    )
    module._set_handle(operator._handle)
    torch_op = getattr(getattr(torch.ops, library), name)
    wrapper = _public_wrapper(library, name, kernel_def, torch_op, operator)
    _registrations[key] = wrapper
    return wrapper


__all__ = ["register_torch_operator"]
