"""Generate and load stable Torch bridges from a native :class:`KernelDef`.

The generated extension contains only Torch-to-``CallAbi`` adaptation and a
process-local operator handle. Kernel selection, caching, and JIT compilation
remain in vecops C++ runtime code, so a call never uses a Python dispatch
callback. The module-level template is intentionally kept outside generation
functions to make its ABI surface reviewable as ordinary source text.
"""

from __future__ import annotations

import ctypes
import hashlib
import keyword
import os
import re
import shutil
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from string import Template
from threading import Lock
from typing import Any

from . import _C as native

@dataclass
class _BridgeRegistration:
  library: str
  name: str
  operator: native.Operator
  kernel_def: native.KernelDef
  compiler: Any
  build_directory: str | os.PathLike[str] | None
  verbose: bool
  extra_cflags: tuple[str, ...]
  return_outputs: bool
  wrapper: Any = None
  materialized: bool = False
  library_path: Path | None = None
  ready: list[bool] = field(default_factory=lambda: [False])
  torch_op: list[Any] = field(default_factory=lambda: [None])


_registrations: dict[tuple[str, str], _BridgeRegistration] = {}
_registration_lock = Lock()
_materialize_lock = Lock()
_loaded_bridge_modules: list[Any] = []
_identifier = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _require_identifier(value: str, what: str) -> None:
  """Reject names that cannot safely become generated C++ identifiers."""
  if not _identifier.fullmatch(value) or keyword.iskeyword(value):
    raise ValueError(f"{what} must be a C++ identifier, got {value!r}")


def _dtype_name(dtype: native.DType) -> str:
  return str(dtype).rsplit(".", 1)[-1]


_dtype_abi = {
  "bool_": "VECOPS_DTYPE_BOOL",
  "int8": "VECOPS_DTYPE_I8",
  "uint8": "VECOPS_DTYPE_U8",
  "int16": "VECOPS_DTYPE_I16",
  "uint16": "VECOPS_DTYPE_U16",
  "int32": "VECOPS_DTYPE_I32",
  "uint32": "VECOPS_DTYPE_U32",
  "int64": "VECOPS_DTYPE_I64",
  "uint64": "VECOPS_DTYPE_U64",
  "float16": "VECOPS_DTYPE_F16",
  "bfloat16": "VECOPS_DTYPE_BF16",
  "float32": "VECOPS_DTYPE_F32",
  "float64": "VECOPS_DTYPE_F64",
}


def _scalar_cpp(dtype: native.DType) -> str:
  name = _dtype_name(dtype)
  if name == "bool_":
    return "bool"
  if name.startswith("float") or name == "bfloat16":
    return "double"
  return "int64_t"


def _scalar_schema(dtype: native.DType) -> str:
  name = _dtype_name(dtype)
  if name == "bool_":
    return "bool"
  if name.startswith("float") or name == "bfloat16":
    return "float"
  return "int"


def _schema_default(value: Any) -> str:
  if isinstance(value, bool):
    return "True" if value else "False"
  return repr(value)


def _torch_schema(
    name: str, definition: native.KernelDef, *, return_outputs: bool = False
) -> str:
  """Lower a KernelDef to a mutable out-style Torch dispatcher schema."""
  arguments: list[str] = []
  outputs: list[str] = []
  alias = ord("a")
  parameters = definition.inputs
  for index, parameter in enumerate(parameters):
    _require_identifier(parameter.name, "kernel parameter name")
    if isinstance(parameter, native.TensorDef):
      if parameter.output and parameter.optional:
        raise ValueError("Torch bridge output tensors must be present and caller-allocated")
      if parameter.output:
        tensor_type = f"Tensor({chr(alias)}!)"
        # The public wrapper returns the caller-owned output argument.  The
        # internal Torch op only needs a Tensor result so older Inductor
        # custom-op wrappers do not reject a void return.  Keep the result
        # unannotated: AOT functionalization cannot represent a custom-op
        # output that aliases a mutable argument, while mutation tracking is
        # already carried by the argument's (a!) annotation.
        outputs.append("Tensor")
        alias += 1
      else:
        tensor_type = "Tensor"
      if parameter.optional:
        tensor_type += "?"
      arguments.append(f"{tensor_type} {parameter.name}")
    else:
      item = f"{_scalar_schema(parameter.dtype)} {parameter.name}"
      if parameter.default is not None:
        item += f"={_schema_default(parameter.default.value)}"
      arguments.append(item)
  for symbol, symbol_type in definition.values.items():
    _require_identifier(symbol, "specialization value name")
    torch_type = "int?" if symbol_type == native.ConstInt else "ScalarType?"
    arguments.append(f"{torch_type} __spec_{symbol}=None")
  returns = "()"
  if return_outputs:
    if len(outputs) == 1:
      returns = outputs[0]
    elif outputs:
      returns = f"({', '.join(outputs)})"
  return f"{name}({', '.join(arguments)}) -> {returns}"


_TORCH_BRIDGE_TEMPLATE = Template(
  r"""// Generated by vecops; do not edit.
#include <ATen/ATen.h>
#include <ATen/Parallel.h>
#include <c10/core/ScalarType.h>
#include <torch/library.h>

#include <algorithm>
#include <array>
#include <atomic>
#include <cstdint>
#include <cstring>
#include <exception>
#include <optional>
#include <tuple>
#include <vector>

#include "vecops/runtime/OperatorBridgeAbi.h"

namespace {
using OperatorInvoke = decltype(&vecops_operator_bridge_invoke_v1);
std::atomic<uint64_t> operator_handle{0};
std::atomic<OperatorInvoke> operator_invoke{nullptr};

uint32_t dtype_to_abi(c10::ScalarType dtype) {
  switch (dtype) {
  case c10::ScalarType::Bool: return VECOPS_DTYPE_BOOL;
  case c10::ScalarType::Char: return VECOPS_DTYPE_I8;
  case c10::ScalarType::Byte: return VECOPS_DTYPE_U8;
  case c10::ScalarType::Short: return VECOPS_DTYPE_I16;
  case c10::ScalarType::Int: return VECOPS_DTYPE_I32;
  case c10::ScalarType::Long: return VECOPS_DTYPE_I64;
  case c10::ScalarType::Half: return VECOPS_DTYPE_F16;
  case c10::ScalarType::BFloat16: return VECOPS_DTYPE_BF16;
  case c10::ScalarType::Float: return VECOPS_DTYPE_F32;
  case c10::ScalarType::Double: return VECOPS_DTYPE_F64;
  default: TORCH_CHECK(false, "vecops does not support Torch dtype ", dtype);
  }
}

VecopsValue make_tensor(const at::Tensor* tensor, uint64_t flags) {
  VecopsValue value{}; value.struct_size = sizeof(VecopsValue);
  if (!tensor) { value.kind = VECOPS_VALUE_NONE; return value; }
  TORCH_CHECK(tensor->defined(), "vecops received an undefined tensor");
  TORCH_CHECK(tensor->device().is_cpu(), "vecops generated bridge currently accepts CPU tensors only");
  TORCH_CHECK(tensor->layout() == c10::Layout::Strided, "vecops requires strided Torch tensors");
  const auto sizes = tensor->sizes();
  const auto strides = tensor->strides();
  value.kind = VECOPS_VALUE_TENSOR;
  value.value.tensor = VecopsTensorView{
    sizeof(VecopsTensorView),
    (flags & VECOPS_TENSOR_WRITE) ? const_cast<at::Tensor*>(tensor)->mutable_data_ptr()
                                  : const_cast<void*>(tensor->const_data_ptr()),
    0, VECOPS_DEVICE_CPU, tensor->device().index(), dtype_to_abi(tensor->scalar_type()),
    static_cast<uint32_t>(tensor->dim()), sizes.data(), strides.data(),
    flags
  };
  return value;
}

VecopsValue make_signed_value(int64_t input, uint32_t dtype) {
  VecopsValue value{}; value.struct_size = sizeof(value); value.kind = VECOPS_VALUE_SCALAR;
  value.value.scalar.struct_size = sizeof(VecopsScalar); value.value.scalar.dtype = dtype;
  value.value.scalar.value.i64 = input; return value;
}
VecopsValue make_unsigned_value(uint64_t input, uint32_t dtype) {
  VecopsValue value{}; value.struct_size = sizeof(value); value.kind = VECOPS_VALUE_SCALAR;
  value.value.scalar.struct_size = sizeof(VecopsScalar); value.value.scalar.dtype = dtype;
  value.value.scalar.value.u64 = input; return value;
}
VecopsValue make_float_value(double input, uint32_t dtype) {
  VecopsValue value{}; value.struct_size = sizeof(value); value.kind = VECOPS_VALUE_SCALAR;
  value.value.scalar.struct_size = sizeof(VecopsScalar); value.value.scalar.dtype = dtype;
  value.value.scalar.value.f64 = input; return value;
}
VecopsSpecializationArgument make_integer_spec(const char* name, int64_t input) {
  VecopsSpecializationArgument value{}; value.struct_size = sizeof(value);
  value.kind = VECOPS_SPECIALIZATION_CONST_INT; value.name = name; value.value.integer = input; return value;
}
VecopsSpecializationArgument make_dtype_spec(const char* name, uint32_t input) {
  VecopsSpecializationArgument value{}; value.struct_size = sizeof(value);
  value.kind = VECOPS_SPECIALIZATION_DTYPE; value.name = name; value.value.dtype = input; return value;
}

uint32_t torch_max_parallelism(void*) {
  return static_cast<uint32_t>(std::max(1, at::get_num_threads()));
}

uint32_t torch_in_parallel_region(void*) {
  return at::in_parallel_region() ? 1u : 0u;
}

int32_t torch_parallel_for(void*, uint32_t task_count, void* body_context,
                           VecopsParallelTaskFn body, VecopsError* error) {
  if (body == nullptr)
    return VECOPS_STATUS_OK;
  try {
    if (task_count <= 1 || at::in_parallel_region()) {
      for (uint32_t task = 0; task < task_count; ++task)
        body(body_context, task, task_count);
    } else {
      at::parallel_for(0, task_count, 1, [=](int64_t begin, int64_t end) {
        for (int64_t task = begin; task < end; ++task)
          body(body_context, static_cast<uint32_t>(task), task_count);
      });
    }
    return VECOPS_STATUS_OK;
  } catch (const std::exception& exception) {
    if (error != nullptr && error->struct_size >= sizeof(VecopsError)) {
      error->code = VECOPS_STATUS_EXECUTION_ERROR;
      const auto size = std::strlen(exception.what());
      error->message_required = size + 1;
      if (error->message != nullptr && error->message_capacity != 0) {
        const auto copied = std::min(size, error->message_capacity - 1);
        std::memcpy(error->message, exception.what(), copied);
        error->message[copied] = '\0';
      }
    }
    return VECOPS_STATUS_EXECUTION_ERROR;
  } catch (...) {
    return VECOPS_STATUS_EXECUTION_ERROR;
  }
}

const VecopsThreadPoolV1 torch_thread_pool{
  sizeof(VecopsThreadPoolV1), VECOPS_THREAD_POOL_ABI_MAJOR,
  VECOPS_THREAD_POOL_ABI_MINOR, UINT64_C(0x746f726368), nullptr,
  &torch_max_parallelism, &torch_in_parallel_region, &torch_parallel_for,
  nullptr, nullptr, 0
};

$cpp_return_type wrapper($cpp_parameters) {
  std::array<VecopsValue, $parameter_count> values{};
$append_arguments
  std::array<VecopsSpecializationArgument, $specialization_count> specs{};
  uint32_t spec_count = 0;
$append_specializations
  VecopsExecutionContext execution_context{};
  execution_context.struct_size = sizeof(VecopsExecutionContext);
  execution_context.requested_threads = torch_max_parallelism(nullptr);
  execution_context.thread_pool = &torch_thread_pool;
  VecopsCall call{sizeof(VecopsCall), static_cast<uint32_t>(values.size()), values.data(), nullptr, 0,
                  &execution_context};
  std::array<char, 1024> message{};
  VecopsError error{sizeof(VecopsError), 0, message.data(), message.size(), 0};
  const auto invoke = operator_invoke.load(std::memory_order_acquire);
  TORCH_CHECK(invoke != nullptr, "vecops bridge has no runtime entry point");
  const auto result = invoke(
    operator_handle.load(std::memory_order_acquire), &call, spec_count, specs.data(), &error);
  TORCH_CHECK(result == VECOPS_STATUS_OK, message.data());
$return_outputs
}

$cpp_return_type meta_wrapper($cpp_parameters) {
$return_outputs
}
} // namespace

TORCH_LIBRARY_FRAGMENT($library, library) {
  library.def("$schema");
}
TORCH_LIBRARY_IMPL($library, CPU, library) {
  library.impl("$name", &wrapper);
}
TORCH_LIBRARY_IMPL($library, Meta, library) {
  library.impl("$name", &meta_wrapper);
}

extern "C" VECOPS_RUNTIME_EXPORT void vecops_torch_bridge_set_handle_v1(
    uint64_t handle, OperatorInvoke invoke) {
  operator_invoke.store(invoke, std::memory_order_release);
  operator_handle.store(handle, std::memory_order_release);
}
"""
)


def _generate_torch_source(
    library: str,
    name: str,
    definition: native.KernelDef,
    *,
    return_outputs: bool = False,
) -> str:
  """Generate the complete bridge translation unit without writing it to disk."""
  schema = _torch_schema(
      name, definition, return_outputs=return_outputs
  ).replace("\\", "\\\\").replace('"', '\\"')
  parameters = definition.inputs
  cpp_parameters: list[str] = []
  call_append: list[str] = []
  for index, parameter in enumerate(parameters):
    local = f"p{index}"
    if isinstance(parameter, native.TensorDef):
      access = parameter.access
      flags = (
        "VECOPS_TENSOR_READ | VECOPS_TENSOR_WRITE"
        if access == native.TensorAccess.inout
        else "VECOPS_TENSOR_WRITE"
        if access == native.TensorAccess.output
        else "VECOPS_TENSOR_READ"
      )
      if parameter.optional:
        cpp_parameters.append(f"std::optional<at::Tensor> {local}")
        call_append.append(f"  values[{index}] = make_tensor({local}.has_value() ? &*{local} : nullptr, {flags});")
      else:
        tensor_type = "at::Tensor&" if parameter.output else "const at::Tensor&"
        cpp_parameters.append(f"{tensor_type} {local}")
        call_append.append(f"  values[{index}] = make_tensor(&{local}, {flags});")
    else:
      cpp_parameters.append(f"{_scalar_cpp(parameter.dtype)} {local}")
      dtype = _dtype_abi[_dtype_name(parameter.dtype)]
      kind = _dtype_name(parameter.dtype)
      if kind == "bool_" or kind.startswith("uint"):
        storage = f"make_unsigned_value({local}, {dtype})"
      elif kind.startswith("int"):
        storage = f"make_signed_value({local}, {dtype})"
      else:
        storage = f"make_float_value({local}, {dtype})"
      call_append.append(f"  values[{index}] = {storage};")

  spec_append: list[str] = []
  for index, (symbol, symbol_type) in enumerate(definition.values.items()):
    local = f"s{index}"
    if symbol_type == native.ConstInt:
      cpp_parameters.append(f"std::optional<int64_t> {local}")
      spec_append.append(f'  if ({local}) specs[spec_count++] = make_integer_spec("{symbol}", *{local});')
    else:
      cpp_parameters.append(f"std::optional<c10::ScalarType> {local}")
      spec_append.append(f'  if ({local}) specs[spec_count++] = make_dtype_spec("{symbol}", dtype_to_abi(*{local}));')

  output_locals = [
      f"p{index}"
      for index, parameter in enumerate(parameters)
      if isinstance(parameter, native.TensorDef) and parameter.output
  ]
  cpp_return_type = "void"
  return_statement = ""
  if return_outputs and len(output_locals) == 1:
    cpp_return_type = "at::Tensor"
    return_statement = f"  return {output_locals[0]};"
  elif return_outputs and output_locals:
    cpp_return_type = "std::tuple<" + ", ".join(
        "at::Tensor" for _ in output_locals
    ) + ">"
    return_statement = f"  return std::make_tuple({', '.join(output_locals)});"

  return _TORCH_BRIDGE_TEMPLATE.substitute(
    schema=schema,
    cpp_parameters=", ".join(cpp_parameters),
    parameter_count=len(parameters),
    append_arguments=os.linesep.join(call_append),
    specialization_count=len(definition.values),
    append_specializations=os.linesep.join(spec_append),
    cpp_return_type=cpp_return_type,
    return_outputs=return_statement,
    library=library,
    name=name,
  )


def _public_wrapper(
    library: str,
    name: str,
    definition: native.KernelDef,
    operator: native.Operator,
    ready: list[bool],
    torch_op_holder: list[Any],
):
  """Wrap raw ``torch.ops`` positional specializations in the public call form."""
  parameters = list(definition.inputs)
  symbols = list(definition.values)
  output_indices = [
    index for index, parameter in enumerate(parameters) if isinstance(parameter, native.TensorDef) and parameter.output
  ]

  def invoke(*args, **kwargs):
    if len(args) > len(parameters):
      raise TypeError(f"{library}.{name} expected at most {len(parameters)} positional arguments")
    ordered = list(args)
    for parameter in parameters[len(ordered) :]:
      if parameter.name in kwargs:
        ordered.append(kwargs.pop(parameter.name))
      elif isinstance(parameter, native.TensorDef) and parameter.optional:
        ordered.append(None)
      elif isinstance(parameter, native.ValueDef) and parameter.default is not None:
        ordered.append(parameter.default.value)
      else:
        raise TypeError(f"missing required argument: {parameter.name}")
    spec_values = [kwargs.pop(symbol, None) for symbol in symbols]
    if kwargs:
      unexpected = next(iter(kwargs))
      raise TypeError(f"unexpected keyword argument: {unexpected}")
    outputs = tuple(ordered[index] for index in output_indices)
    from ._precompile import maybe_collect_call

    collected = maybe_collect_call(
      operator,
      definition,
      ordered,
      dict(zip(symbols, spec_values)),
      name=f"{library}::{name}",
    )
    if not collected:
      if not ready[0]:
        compile_pending_torch_bridges()
      torch_op = torch_op_holder[0]
      torch_op(*ordered, *spec_values)
    if len(outputs) == 1:
      return outputs[0]
    return outputs

  invoke.__name__ = name
  invoke.__qualname__ = f"vecops.ops.torch.{library}.{name}"
  invoke.__doc__ = f"Generated mutable vecops wrapper for {library}::{name}."
  invoke._vecops_operator = operator
  return invoke


def _bridge_include_root() -> Path:
  include_root = Path(__file__).resolve().parents[2] / "include"
  configured_root = os.environ.get("VECOPS_SOURCE_ROOT")
  if configured_root:
    include_root = Path(configured_root).expanduser().resolve() / "include"
  if (include_root / "vecops" / "runtime" / "OperatorBridgeAbi.h").is_file():
    return include_root
  packaged = Path(__file__).resolve().parent / "_sdk" / "include"
  if (packaged / "vecops" / "runtime" / "OperatorBridgeAbi.h").is_file():
    return packaged
  raise RuntimeError("vecops framework bridge headers were not found")


def _cached_bridge(directory: Path, output_name: str) -> Path | None:
  if not directory.is_dir():
    return None
  candidates = [
      path
      for path in directory.iterdir()
      if path.is_file()
      and path.suffix in {".so", ".dylib", ".dll"}
      and output_name in path.name
  ]
  return candidates[0] if len(candidates) == 1 else None


def _toolchain_key(config: native.KernelCompilerConfig) -> tuple[Any, ...]:
  toolchain = config.toolchain
  return (
      str(config.sdk.path),
      config.sdk.layout,
      str(toolchain.cmake_program),
      str(toolchain.c_compiler),
      str(toolchain.cxx_compiler),
      str(toolchain.toolchain_file),
      toolchain.generator,
      toolchain.build_type,
      tuple(sorted(toolchain.environment.items())),
  )


def _copy_toolchain(toolchain: native.ToolchainSpec) -> native.ToolchainSpec:
  copied = native.ToolchainSpec()
  copied.cmake_program = toolchain.cmake_program
  copied.c_compiler = toolchain.c_compiler
  copied.cxx_compiler = toolchain.cxx_compiler
  copied.toolchain_file = toolchain.toolchain_file
  copied.generator = toolchain.generator
  copied.build_type = toolchain.build_type
  copied.parallel_jobs = toolchain.parallel_jobs
  copied.environment = toolchain.environment
  return copied


def _torch_openmp_runtime(
    torch_libraries: tuple[Path, ...], torch_parallel_info: str
) -> str | None:
  if "ATen parallel backend: OpenMP" not in torch_parallel_info:
    return None
  runtime_names = {
      "gomp": ("libgomp.so*", "libgomp.dylib"),
      "omp": ("libomp.so*", "libomp.dylib", "libiomp5.so*", "libiomp5.dylib"),
  }
  detected = {
      runtime
      for directory in torch_libraries
      for runtime, patterns in runtime_names.items()
      if any(any(directory.glob(pattern)) for pattern in patterns)
  }
  if len(detected) != 1:
    detail = ", ".join(sorted(detected)) or "none"
    raise RuntimeError(
        "Torch reports its OpenMP backend, but its packaged OpenMP runtime "
        f"could not be identified unambiguously (found: {detail})"
    )
  return detected.pop()


def _torch_bridge_build_policy(
    config: native.KernelCompilerConfig,
    torch_libraries: tuple[Path, ...],
    torch_parallel_info: str,
) -> tuple[native.ToolchainSpec, tuple[str, ...]]:
  """Enable the header-only ATen parallel backend with a matching runtime."""
  toolchain = _copy_toolchain(config.toolchain)
  runtime = _torch_openmp_runtime(torch_libraries, torch_parallel_info)
  if runtime is None:
    return toolchain, ()

  compiler_name = Path(toolchain.cxx_compiler).name.lower()
  compiler_is_clang = "clang" in compiler_name
  compiler_is_gnu = not compiler_is_clang and (
      "g++" in compiler_name or "gcc" in compiler_name
  )
  if runtime == "gomp" and not compiler_is_gnu:
    requested_cxx = os.environ.get("VECOPS_TORCH_BRIDGE_CXX", "g++")
    requested_cc = os.environ.get("VECOPS_TORCH_BRIDGE_CC", "gcc")
    bridge_cxx = shutil.which(requested_cxx)
    bridge_cc = shutil.which(requested_cc)
    if bridge_cxx is None or bridge_cc is None:
      raise RuntimeError(
          "Torch uses GNU OpenMP, but the selected kernel compiler cannot "
          "emit its ABI and a GNU bridge compiler was not found; install "
          "gcc/g++ or set VECOPS_TORCH_BRIDGE_CC and VECOPS_TORCH_BRIDGE_CXX"
      )
    toolchain.c_compiler = Path(bridge_cc).absolute()
    toolchain.cxx_compiler = Path(bridge_cxx).absolute()
    return toolchain, ("-fopenmp",)
  if runtime == "gomp":
    return toolchain, ("-fopenmp",)
  if runtime == "omp" and compiler_is_clang:
    return toolchain, ("-fopenmp=libomp",)
  requested_cxx = os.environ.get("VECOPS_TORCH_BRIDGE_CXX", "clang++")
  requested_cc = os.environ.get("VECOPS_TORCH_BRIDGE_CC", "clang")
  bridge_cxx = shutil.which(requested_cxx)
  bridge_cc = shutil.which(requested_cc)
  if bridge_cxx is None or bridge_cc is None:
    raise RuntimeError(
        "Torch uses LLVM/Intel OpenMP, but the selected kernel compiler "
        "cannot emit its ABI and a Clang bridge compiler was not found; "
        "install clang or set VECOPS_TORCH_BRIDGE_CC and "
        "VECOPS_TORCH_BRIDGE_CXX"
    )
  toolchain.c_compiler = Path(bridge_cc).absolute()
  toolchain.cxx_compiler = Path(bridge_cxx).absolute()
  return toolchain, ("-fopenmp=libomp",)


def _load_bridge(
    registration: _BridgeRegistration,
    library_path: Path,
    native_library: Path,
    torch: Any,
) -> None:
  torch.ops.load_library(str(library_path))
  module = ctypes.CDLL(str(library_path))
  native_module = ctypes.CDLL(str(native_library))
  invoke = ctypes.cast(
      native_module.vecops_operator_bridge_invoke_v1, ctypes.c_void_p
  )
  setter = module.vecops_torch_bridge_set_handle_v1
  setter.argtypes = [ctypes.c_uint64, ctypes.c_void_p]
  setter.restype = None
  setter(registration.operator._handle, invoke)
  _loaded_bridge_modules.extend((module, native_module))
  registration.library_path = library_path
  registration.materialized = True
  registration.torch_op[0] = getattr(getattr(torch.ops, registration.library), registration.name)
  registration.ready[0] = True


def _compile_pending_torch_bridges_impl(*, parallelism: int | None = None) -> int:
  """Build every pending Torch bridge through shared CMake batches."""
  if parallelism is not None and (
      isinstance(parallelism, bool) or parallelism < 1
  ):
    raise ValueError("parallelism must be a positive integer")
  with _materialize_lock:
    with _registration_lock:
      pending = [item for item in _registrations.values() if not item.materialized]
    if not pending:
      return 0

    import torch
    from torch.utils.cpp_extension import include_paths, library_paths

    include_root = _bridge_include_root()
    torch_includes = tuple(Path(path).resolve() for path in include_paths("cpu"))
    torch_libraries = tuple(Path(path).resolve() for path in library_paths("cpu"))
    torch_parallel_info = torch.__config__.parallel_info()
    native_library = Path(native.__file__).resolve()
    torch_identity = (
        torch.__version__,
        torch.compiled_with_cxx11_abi(),
        tuple(map(str, torch_includes)),
        tuple(map(str, torch_libraries)),
        torch_parallel_info,
    )

    groups: dict[tuple[Any, ...], list[tuple[_BridgeRegistration, Any]]] = {}
    for registration in pending:
      config = registration.compiler._native_config()
      if parallelism is not None:
        toolchain = config.toolchain
        toolchain.parallel_jobs = parallelism
        config.toolchain = toolchain
      groups.setdefault(_toolchain_key(config), []).append((registration, config))

    built_count = 0
    for group in groups.values():
      first_registration, first_config = group[0]
      bridge_toolchain, bridge_openmp_flags = _torch_bridge_build_policy(
          first_config, torch_libraries, torch_parallel_info
      )
      first_registration.compiler.build_dir.mkdir(parents=True, exist_ok=True)
      attempt = Path(
          tempfile.mkdtemp(
              prefix="torch-bridge-batch-",
              dir=first_registration.compiler.build_dir,
          )
      )
      batch = native.KernelBuildBatchRequest()
      batch.generated_source_directory = attempt / "project"
      batch.build_directory = attempt / "build"
      tasks = []
      task_registrations = []
      resolved: dict[tuple[str, str], Path] = {}

      for index, (registration, config) in enumerate(group):
        source = _generate_torch_source(
            registration.library,
            registration.name,
            registration.kernel_def,
            return_outputs=registration.return_outputs,
        )
        bridge_identity = (
            "torch-bridge-v3",
            str(bridge_toolchain.c_compiler),
            str(bridge_toolchain.cxx_compiler),
            tuple(bridge_openmp_flags),
        )
        identity = repr(
            (source, torch_identity, _toolchain_key(config), bridge_identity)
        )
        digest = hashlib.sha256(identity.encode()).hexdigest()[:16]
        output_name = (
            f"vecops_bridge_{registration.library}_{registration.name}_{digest}"
        )
        if registration.build_directory is None:
          from ._compiler import default_cache_dir

          override = os.environ.get("VECOPS_TORCH_BRIDGE_DIR")
          bridge_base = (
              Path(override).expanduser().resolve()
              if override
              else default_cache_dir() / "torch-bridges-v3"
          )
          artifact_directory = bridge_base / (
              f"{registration.library}_{registration.name}_{digest}"
          )
        else:
          artifact_directory = Path(registration.build_directory).expanduser().resolve()
        cached = _cached_bridge(artifact_directory, output_name)
        if cached is not None:
          resolved[(registration.library, registration.name)] = cached
          continue

        input_directory = attempt / "inputs" / str(index)
        input_directory.mkdir(parents=True, exist_ok=True)
        source_path = input_directory / "bridge.cpp"
        source_path.write_text(source)
        request = native.KernelBuildRequest()
        request.target_name = output_name
        request.output_name = output_name
        request.sdk = config.sdk
        request.toolchain = bridge_toolchain
        request.sources = [source_path]
        request.include_directories = [include_root, *torch_includes]
        request.compile_definitions = [
            f"_GLIBCXX_USE_CXX11_ABI={int(torch.compiled_with_cxx11_abi())}"
        ]
        request.compile_options = [
            "-O3", "-std=c++20",
            *bridge_openmp_flags,
            *registration.extra_cflags,
        ]
        request.link_directories = list(torch_libraries)
        request.link_libraries = ["torch", "torch_cpu", "c10"]
        request.link_options = [
            *bridge_openmp_flags,
            *(f"-Wl,-rpath,{path}" for path in torch_libraries),
        ]
        request.generated_source_directory = batch.generated_source_directory / "tasks" / str(index)
        request.build_directory = batch.build_directory / "tasks" / str(index)
        request.artifact_directory = artifact_directory
        tasks.append(request)
        task_registrations.append(registration)

      if tasks:
        batch.tasks = tasks
        result = first_registration.compiler.build_backend.compile_batch(batch)
        if not result.success:
          detail = result.error
          if result.configure is not None and result.configure.output:
            detail += "\n[configure]\n" + result.configure.output
          if result.build is not None and result.build.output:
            detail += "\n[build]\n" + result.build.output
          raise RuntimeError(f"Torch bridge batch compilation failed: {detail}")
        for registration, task_result in zip(task_registrations, result.tasks):
          if not task_result.success or task_result.kernel_library is None:
            raise RuntimeError(
                f"Torch bridge {registration.library}::{registration.name} "
                f"did not produce a shared library: {task_result.error}"
            )
          resolved[(registration.library, registration.name)] = Path(
              task_result.kernel_library
          )
          built_count += 1

      for registration, _ in group:
        path = resolved[(registration.library, registration.name)]
        _load_bridge(registration, path, native_library, torch)
    return built_count


def compile_pending_torch_bridges(*, parallelism: int | None = None) -> int:
  """Build pending bridges while coalescing cache writers across processes."""
  from ._compiler import require_native_build_api

  require_native_build_api()
  if parallelism is not None and (
      isinstance(parallelism, bool) or parallelism < 1
  ):
    raise ValueError("parallelism must be a positive integer")
  with _registration_lock:
    if all(item.materialized for item in _registrations.values()):
      return 0
  try:
    import fcntl
  except ImportError:
    return _compile_pending_torch_bridges_impl(parallelism=parallelism)
  from ._compiler import default_cache_dir

  override = os.environ.get("VECOPS_TORCH_BRIDGE_DIR")
  lock_root = (
      Path(override).expanduser().resolve()
      if override
      else default_cache_dir() / "torch-bridges-v3"
  )
  lock_root.mkdir(parents=True, exist_ok=True)
  with (lock_root / ".compile.lock").open("a+b") as lock:
    fcntl.flock(lock.fileno(), fcntl.LOCK_EX)
    try:
      return _compile_pending_torch_bridges_impl(parallelism=parallelism)
    finally:
      fcntl.flock(lock.fileno(), fcntl.LOCK_UN)


def register_torch_operator(
  library: str,
  name: str,
  operator: native.Operator,
  kernel_def: native.KernelDef,
  *,
  compiler: Any,
  build_directory: str | os.PathLike[str] | None = None,
  verbose: bool = False,
  extra_cflags: tuple[str, ...] = (),
  return_outputs: bool = False,
):
  """Declare one mutable Torch bridge and return its public wrapper.

  Registration is idempotent per ``(library, name)`` in this Python process.
  Registration queues a content-addressed build task. Pending tasks are
  materialized together by :func:`compile_pending_torch_bridges`, or lazily by
  the first real wrapper invocation.
  """
  _require_identifier(library, "Torch library name")
  _require_identifier(name, "Torch operator name")
  key = (library, name)
  with _registration_lock:
    if key in _registrations:
      return _registrations[key].wrapper
    registration = _BridgeRegistration(
      library=library,
      name=name,
      operator=operator,
      kernel_def=kernel_def,
      compiler=compiler,
      build_directory=build_directory,
      verbose=verbose,
      extra_cflags=tuple(extra_cflags),
      return_outputs=return_outputs,
    )
    registration.wrapper = _public_wrapper(
        library,
        name,
        kernel_def,
        operator,
        registration.ready,
        registration.torch_op,
    )
    _registrations[key] = registration
    return registration.wrapper


__all__ = ["compile_pending_torch_bridges", "register_torch_operator"]
